# deployment/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # FastAPI application metrics
  - job_name: 'changi-chatbot-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node exporter for system metrics (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Alerting rules (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Example alerting rules
# groups:
#   - name: changi-chatbot
#     rules:
#     - alert: HighErrorRate
#       expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
#       for: 5m
#       labels:
#         severity: warning
#       annotations:
#         summary: High error rate detected
#         description: "Error rate is {{ $value }} errors per second"
#
#     - alert: HighResponseTime
#       expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
#       for: 5m
#       labels:
#         severity: warning
#       annotations:
#         summary: High response time detected
#         description: "95th percentile response time is {{ $value }} seconds"